apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: nextflow-role_nextflow-sa
 namespace: default
roleRef:
 kind: Role
 name: nextflow-role
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: nextflow-sa
   namespace: default
